[dr]
type = drive
scope = drive
token = {"access_token":"ya29.a0AeXRPp6jgnbofOC9EJqFVLiRedDQ-PUCxGNRbzdgzvVhHiSWmzT7unkIfBNMGk1t1TZn9t_ijI1RQ0fuHoko79clrwQ3yWvyEHIL553Pp6vl3Dmf01z4UOu_4NNJI0EiMggSVXrP-i-BR8mELqULlmVY70Pz9n1EI7U2tQL6aCgYKAd0SARMSFQHGX2MiqDMUMUWw21deRWTkqBOR4Q0175","token_type":"Bearer","refresh_token":"1//0gzToJ9eGm2H0CgYIARAAGBASNwF-L9IrUslCWpbbGdjdRuBLGfNtnPvWSUutDhFNihPm2jc2MBpuQsoN8cVIgeqliQLKFos7aSI","expiry":"2025-03-17T18:02:43.701045762Z"}